### PR TITLE
Update version to 2.4.0

### PR DESCRIPTION
**Pull request by sergei-ivanov**
Improve system architecture detection

Signed-off-by: Sergey Ivanov <sergey.ivanov@weareadaptive.com>

### CODE REVIEW

**Comment by sergei-ivanov** [comment]
I have tested it locally (Ubuntu 20.04 Focal on x64) using `run-tests.sh`, and I have checked platform detection on two colleagues' MacBooks (Intel and M1), and on an AWS Graviton2 instance. Please test it with some other OS / architecture combinations if you can.

**Comment by sergei-ivanov** [comment]
Tested on Apple M1 MacBook Pro to correctly download and use arm64 binary.

**Review by mstruebing — APPROVED** [review]
Thank you very mich 👍

**Comment by sergei-ivanov** [comment]
Can you please publish the package for 2.4.0 to pypi.org?

**Comment by mstruebing** [comment]
I don't know how - What do I need to do?

**Comment by mmicu** [comment]
Currently, I am the only one that can publish the package.

I cannot upload it right now, but probably I can do it in the evening.

Maybe next time we could wait before merging the change.

**Comment by mstruebing** [comment]
> Maybe next time we could wait before merging the change.

Sorry, that's my bad - I will wait next time.

**Comment by mmicu** [comment]
> > Maybe next time we could wait before merging the change.
> 
> Sorry, that's my bad - I will wait next time.

No worries.


> Can you please publish the package for 2.4.0 to pypi.org?

Package has been published. Thanks for your contribution.

**Comment by sergei-ivanov** [comment]
Sorry, guys. I feel like I caused a bit of trouble here :)

Thank you very much for maintaining this project.

**Comment by mmicu** [comment]
No worries :)

Now we are better organized for next time!

**Pull request merged**
